import polars as pl
import matplotlib.pyplot as plt

import numpy as np
import scipy.stats



def make_gene_id_lookup(idmap_path):

    """
    This function parses a uniprot id map files and returns a dictionary mapping uniprot ids to ensembl gene ids
    """

    uniprot_to_geneid = {}

    with open(idmap_path, 'r') as f:
        for l in f:
            uniprot, etype, value = l.strip('\n').split()[:3]
            if etype == "TAIR":
                uniprot_to_geneid[uniprot] = value

    return uniprot_to_geneid




def map_to_ensembl_id(uniprot_ids, id_lookup):

    """
    This function converts a string of uniprot_ids seperated by ; to a list of ensembl gene ids using the dictionary generated by make_gene_id_lookup
    """

    gene_ids = []

    uniprot_ids = uniprot_ids.split(';')
    for uid in uniprot_ids:
        if uid in id_lookup:
            gene_ids.append(id_lookup[uid])

    return gene_ids        



def plot_replicates(df, replicate_groups, outpath ='gene_enrichment_correlation_shoots.pdf'):

    fig,ax = plt.subplots(2,3)
    ax = np.ravel(ax)

    for i,(rgroup,(r1,r2)) in enumerate(replicate_groups.items()):

        r1 = df.select(r1)
        r2 = df.select(r2)

        ax[i].scatter(r1,r2, s = 1)
        ax[i].set_xscale('log')
        ax[i].set_yscale('log')
        
        corr, pval = scipy.stats.spearmanr(r1,r2,nan_policy='omit')


        ax[i].set_title(f'{rgroup} \n r = {corr:.2f} pval = {pval}', fontsize = 6)

    fig.tight_layout()

    fig.savefig(outpath)
        








def process_data(df, id_lookup, experimental_conditions = ['10°C', '20°C', '30°C'], treatment_id = '15GLY-15SER_shoot', control_id = 'GLY-SER_shoot', sample_id = "normalized_gene_enrichment"):
    
    """
    This function converts a dataframe consisting of peptide fragments to genes. 

    df: polars dataframe
    id_lookup: dict generated from make_gene_id_lookup
    experimental_conditions: list of sample prefixes
    treatment_id: str identifying treatment label
    control_id: str identifying control label
    sample_id: str data label from output dataframe
    
    function returns a polars dataframe
    """

    #This substitutes ensembl_ids for uni_prot_ids when possible. Mean enrichments are averaged across genes. For peptides that match to multiple fragments the rows are duplicated.

    df = df.with_columns(pl.col('protein_group').map_elements(lambda a: map_to_ensembl_id(a,id_lookup), return_dtype=pl.List(pl.String)).alias('gene_ids')).select(['normalized_mean_enrichment','sample','gene_ids']).explode('gene_ids').group_by(['sample','gene_ids']).agg(pl.mean('normalized_mean_enrichment').alias('gene_enrichment'))

    df= df.pivot(on = 'sample',values = ['gene_enrichment'])

    replicate_groups = {}

    for c in df.columns[1:]:
        rname = '_'.join(c.split('_')[:-1])
        if rname not in replicate_groups:
            replicate_groups[rname] = []
        replicate_groups[rname].append(c)


    sample_ids = [f'{e}_{sample_id}'for e in experimental_conditions]

    #Here we combine replicates. I required the gene to be presence in both replicates to be included 

    df =df.with_columns(df.select(v).mean_horizontal(ignore_nulls=False).alias(k) for k,v in replicate_groups.items()).select(['gene_ids'] + list(replicate_groups.keys()))

    #Here we subtracted the gene_enrichment of the unlabeled samples from the labeled

    df = df.with_columns((pl.col(f'{t}_{treatment_id}') - pl.col(f'{t}_{control_id}')).alias(f'{t}_{sample_id}') for t in experimental_conditions).select(['gene_ids'] + [f'{t}_{sample_id}' for t in temp]).filter(pl.sum_horizontal(pl.all().is_null()) < len(sample_ids) -1 )

    #negative gene_enrichment values were replaced with 0

    df = df.with_columns(pl.when(pl.col(s) < 0).then(0).otherwise(pl.col(s)).alias(s) for s in sample_ids)

    return df


def get_gene_enrichment(df, q = 0.9):

    """
    This function takes a polars dataframe consiting of normalized enirchment scores for different experimental conditions and returns a dict consiting of keys of experimental conditions and values of ensembl gene_ids
    """

    gene_enrichment = {}

    for c in df.columns[1:]:
        enirched_genes = df.filter(pl.col(c) > np.nanquantile(df.select(c), q)).select('gene_ids').to_numpy().reshape(1,-1).tolist()[0]
        all_genes = df.filter(pl.col(c).is_not_null()).select('gene_ids').to_numpy().reshape(1,-1).tolist()[0]
        gene_enrichment[c] = {'enriched': enirched_genes, 'all' : all_genes}



    return gene_enrichment











id_lookup = make_gene_id_lookup('genome/ARATH_3702_idmapping.dat')
df = pl.read_csv('output/total_proteome/shoots/isocorrected_shoots.csv')
df_processed = process_data(df, id_lookup=id_lookup)

gene_enrichment_groups = get_gene_enrichment(df_processed)





